# this should give us faster builds according to 
# http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false

language: go
go:
  - tip
  - master
  - release
  - 1.9
  - 1.8
  - 1.7
  - 1.6
  - 1.5
  - 1.4
  - 1.3
  - 1.2
  - 1.1

matrix:
  allow_failures:
    - go: tip
    - go: 1.5
    - go: 1.4
    - go: 1.3
    - go: 1.2
    - go: 1.1
  fast_finish: true

before_install:
  - go get github.com/golang/lint/golint

install:
  - # Do nothing. This is needed to prevent default install action "go get -t -v ./..." from happening here (we want it to happen inside script step).

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - go test -v -race ./...
  - go test -v -coverprofile=coverage.txt -covermode=atomic
  - golint ./... # This won't break the build, just show warnings

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
    - Travis.APA@a-bc.net
    on_success: always
    on_failure: always
